// Code generated by github.com/gobuffalo/syncx. DO NOT EDIT.

package syncx

import (
	"sort"
	"sync"

	"github.com/gofrs/uuid"
)

// UUIDMap wraps sync.Map and uses the following types:
// key:   string
// value: uuid.UUID
type UUIDMap struct {
	data sync.Map
}

// Delete the key from the map
func (m *UUIDMap) Delete(key string) {
	m.data.Delete(key)
}

// Load the key from the map.
// Returns uuid.UUID or bool.
// A false return indicates either the key was not found
// or the value is not of type uuid.UUID
func (m *UUIDMap) Load(key string) (uuid.UUID, bool) {
	i, ok := m.data.Load(key)
	if !ok {
		return uuid.Nil, false
	}
	s, ok := i.(uuid.UUID)
	return s, ok
}

// LoadOrStore will return an existing key or
// store the value if not already in the map
func (m *UUIDMap) LoadOrStore(key string, value uuid.UUID) (uuid.UUID, bool) {
	i, _ := m.data.LoadOrStore(key, value)
	s, ok := i.(uuid.UUID)
	return s, ok
}

// Range over the uuid.UUID values in the map
func (m *UUIDMap) Range(f func(key string, value uuid.UUID) bool) {
	m.data.Range(func(k, v interface{}) bool {
		key, ok := k.(string)
		if !ok {
			return false
		}
		value, ok := v.(uuid.UUID)
		if !ok {
			return false
		}
		return f(key, value)
	})
}

// Store a uuid.UUID in the map
func (m *UUIDMap) Store(key string, value uuid.UUID) {
	m.data.Store(key, value)
}

// Keys returns a list of keys in the map
func (m *UUIDMap) Keys() []string {
	var keys []string
	m.Range(func(key string, value uuid.UUID) bool {
		keys = append(keys, key)
		return true
	})
	sort.Strings(keys)
	return keys
}
