// Code generated by github.com/gobuffalo/syncx. DO NOT EDIT.

package syncx

import (
	"testing"

	"github.com/gofrs/uuid"
	"github.com/stretchr/testify/require"
)

func Test_UUIDMap(t *testing.T) {
	r := require.New(t)

	sm := &UUIDMap{}

	sm.Store("a", uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c1")))

	s, ok := sm.Load("a")
	r.True(ok)
	r.Equal(uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c1")), s)

	s, ok = sm.LoadOrStore("b", uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c2")))
	r.True(ok)
	r.Equal(uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c2")), s)

	s, ok = sm.LoadOrStore("b", uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c3")))
	r.True(ok)
	r.Equal(uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c2")), s)

	var keys []string

	sm.Range(func(key string, value uuid.UUID) bool {
		keys = append(keys, key)
		return true
	})

	r.Equal(sm.Keys(), keys)

	sm.Delete("b")
	r.Equal([]string{"a", "b"}, keys)

	sm.Delete("b")
	_, ok = sm.Load("b")
	r.False(ok)

	func(m *UUIDMap) {
		m.Store("c", uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c4")))
	}(sm)
	s, ok = sm.Load("c")
	r.True(ok)
	r.Equal(uuid.Must(uuid.FromString("6ba7b814-9dad-11d1-80b4-00c04fd430c4")), s)
}
