// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "__packr_global__"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"c31566ddedb835e0a8db3db3c68d6f6e": "1f8b08000000000000ffac92ef4ac33014c53fe73ec5753068a4f401440782e017a7a0bec0b5bb1da16d52d2743846df5d9225ee8fc22af83539e79773ef4947654d6bc67eabcb4f00d576c63acc40ccfcc90c2480db768cb7f33b6c8b676a19e78b2575d83b3b940e772056e428f88b2575300254832e316bf1fadc24f1811b769cd5bcf500a5d7d213dac2338ac3a5bc807932b43a81647bcda379f761e78b1c3f8c69025ce5686abcf1d7e195e49520548557a6f62261d90d56c731ef03a1a2a6671023883e215471fe9084640da209b95fec9b33f67807396ea819d28e0fe8bf4e75448e48f98fd95f49af39abd04ba684ff8e1a13467f70e7b841a51ddb8a4ade8d7b71e82164df07ae8b2cd60be2b8aa143af6e30b122143326e7e9bf412211d9d6e6fbcf41327777958c4cf9246f80a0000ffffd96b417887030000",
		"e6327c7fda5eb323af6f336164d82b08": "1f8b08000000000000ff94924f6bdc3010c5cf9a4f3108b6c8c168ef251b68d23f973685666f6109b233718c2dcb19c969cde2ef5e247b376d0281bd19cdbcf73cbf99de948da908fdd8957f006adb3b0ea84048ef38481032900f7557490021ab3a3c0e852e9d5dfbc014ca475ea7fac3b8667a1a6a260919c0c3d095b8251feece571bb4fada58c2d5c50fd3ab80678ba3de66b807c1f871838b585fd36f153200e16d7cfef05abe9f524ddf04c7a4a49139ce2d9f7075917439ba264abdd5df9db98f3d1908d65b1e48b9267d7f791a4cab5e8439fa17ed51fa939794e298729952de71bb3cc9ed14bb67c3d8d0e8f176e703d75d3583f865ba8a54e4ad1a1a712ee5f86cda8196986f6e3bf6915f8685736d642e92d3064ddf53771f953e8fee1908c11406ee30f04020a63489e3a06fdabaa4a533c5991c0bacbbf08feb228d4db76687e7f357b15b7c0eb31d26d8a7fdc9424e297ca666f5676a2924501988bbff292eafacbf9ad6cfc840a4dfb178f6fa58d27989e3b19447f05733f749799bbd59546c7c77295787a54cf0370000ffffa7ddc4183e030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("../maps/templates", "../maps/templates")
		b.SetResolver("map.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "c31566ddedb835e0a8db3db3c68d6f6e"})
		b.SetResolver("map_test.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "e6327c7fda5eb323af6f336164d82b08"})
	}()

	return nil
}()
